#!/bin/sh

MODDIR=/lib/modules

load()
{
  echo "[autofs] Loading autofs"
  if [ -e $MODDIR/autofs4.ko ]; then
    insmod $MODDIR/autofs4.ko
  fi
}

unload()
{
  echo "[autofs] Unloading autofs"
  if [ -e $MODDIR/autofs4.ko ]; then
    rmmod $MODDIR/autofs4.ko
  fi
}

start()
{
  echo "[autofs] Starting autofs"
  /usr/sbin/automount --timeout=5 /autofs file /etc/auto.hotplug
  /usr/sbin/automount --ghost --timeout=5 /media/net file /etc/auto.network
}

stop()
{
  echo "[autofs] Stopping autofs"
  killall automount
}

case "$1" in
  start)
    load
    start
    ;;
  stop)
    stop
    unload
    ;;
  restart)
    stop
    sleep 1
    start
    ;;
  reload)
    stop
    sleep 1
    start
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart|reload}"
    RETVAL=0
esac

